/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.payroll_management_project;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class salarySlip extends javax.swing.JInternalFrame {

    /**
     * Creates new form salarySlip
     */
    public salarySlip() {
        initComponents();
        // SalaryDesktop.setBackground(Color.LIGHT_GRAY);
         Color lightBlue = Color.decode("#ADD8E6");
        this.getContentPane().setBackground( lightBlue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SalaryDesktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        GetSlip = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        department = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        position = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        hours = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        basicPay = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tax = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        bonus = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        grossSalary = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        SalaryDesktop.setBackground(new java.awt.Color(255, 255, 204));
        SalaryDesktop.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SALARY SLIP");

        jLabel2.setText("Emp ID");

        GetSlip.setText("Generate");
        GetSlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetSlipActionPerformed(evt);
            }
        });

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Employee Details");

        jLabel4.setText("Name");

        jLabel5.setText("Email");

        name.setText("jLabel6");

        email.setText("jLabel7");

        jLabel8.setText("Department");

        department.setText("jLabel9");

        jLabel10.setText("Position");

        position.setText("jLabel11");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel12.setText("Working Hours");

        hours.setText("jLabel13");

        jLabel14.setText("Hours");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel17.setText("Earning");

        jLabel18.setText("Basic Pay");

        basicPay.setText("jLabel19");

        jLabel20.setText("Tax");

        tax.setText("jLabel21");

        jLabel22.setText("Bonus");

        bonus.setText("jLabel23");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Gross Salary");

        grossSalary.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        grossSalary.setText("jLabel25");

        jButton1.setText("Print");

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        SalaryDesktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(GetSlip, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(id, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(email, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(department, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(position, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(hours, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(basicPay, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(tax, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(bonus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(grossSalary, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SalaryDesktop.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout SalaryDesktopLayout = new javax.swing.GroupLayout(SalaryDesktop);
        SalaryDesktop.setLayout(SalaryDesktopLayout);
        SalaryDesktopLayout.setHorizontalGroup(
            SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalaryDesktopLayout.createSequentialGroup()
                .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SalaryDesktopLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SalaryDesktopLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SalaryDesktopLayout.createSequentialGroup()
                                .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12))
                                .addGap(65, 65, 65)
                                .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hours)
                                    .addComponent(name)
                                    .addGroup(SalaryDesktopLayout.createSequentialGroup()
                                        .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton1)
                                            .addGroup(SalaryDesktopLayout.createSequentialGroup()
                                                .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(SalaryDesktopLayout.createSequentialGroup()
                                                        .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(email)
                                                            .addComponent(department)
                                                            .addComponent(position))
                                                        .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(SalaryDesktopLayout.createSequentialGroup()
                                                                .addGap(218, 218, 218)
                                                                .addComponent(jLabel17))
                                                            .addGroup(SalaryDesktopLayout.createSequentialGroup()
                                                                .addGap(203, 203, 203)
                                                                .addComponent(jLabel18))))
                                                    .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel22)
                                                        .addComponent(jLabel24)
                                                        .addComponent(jLabel20)))
                                                .addGap(15, 15, 15)))
                                        .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(SalaryDesktopLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton2))
                                            .addGroup(SalaryDesktopLayout.createSequentialGroup()
                                                .addGap(76, 76, 76)
                                                .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(grossSalary)
                                                    .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tax)
                                                        .addComponent(basicPay)
                                                        .addComponent(bonus)))
                                                .addGap(0, 63, Short.MAX_VALUE)))))))))
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SalaryDesktopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SalaryDesktopLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SalaryDesktopLayout.createSequentialGroup()
                        .addComponent(GetSlip)
                        .addGap(146, 146, 146))))
        );
        SalaryDesktopLayout.setVerticalGroup(
            SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalaryDesktopLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GetSlip)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(email))
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(department))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(position)
                    .addComponent(jLabel18)
                    .addComponent(basicPay))
                .addGap(18, 18, 18)
                .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tax))
                .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SalaryDesktopLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(bonus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SalaryDesktopLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(3, 3, 3)))
                .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(grossSalary))
                .addGap(14, 14, 14)
                .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(hours))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(SalaryDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(99, 99, 99))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SalaryDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SalaryDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GetSlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetSlipActionPerformed
        // TODO add your handling code here:
        String empId = id.getText();
        int intId = Integer.parseInt(empId);
        try {
            Class.forName("com.mysql.jdbc.Driver");
          Connection con ;
         
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll_manage", "root", "sql@Lipton");
            
              PreparedStatement ps = con.prepareStatement("select * from emp where empId = ?");
//              ps.setString(1, intId);
              ps.setInt(1, intId);
              
              ResultSet rs = ps.executeQuery();
              if(rs.next() != false){
                   name.setText(rs.getString("name"));
                   email.setText(rs.getString("email"));
                   
                   int depid = Integer.parseInt(rs.getString("depId"));
                   PreparedStatement ps1 = con.prepareStatement("select * from department where depID = ?");
                   ps1.setInt(1, depid);
                   ResultSet rs1 = ps1.executeQuery();
                   if (rs1.next()) {
                        department.setText(rs1.getString("depName"));
                    }
                   
                   int basicpay = 0;
                   int posid = Integer.parseInt(rs.getString("positionId"));
                   PreparedStatement ps2 = con.prepareStatement("select * from position where posID = ?");
                   ps2.setInt(1, posid);
                   ResultSet rs2 = ps2.executeQuery();
                   if (rs2.next()) {
                        position.setText(rs2.getString("posName"));
                        basicPay.setText(rs2.getString("salary"));
                        basicpay = Integer.parseInt(rs2.getString("salary"));
                   }
                   
                    hours.setText(rs.getString("workingDays"));
                    bonus.setText(rs.getString("bonus"));
                    tax.setText("5%");
                    
                    int workingDays = Integer.parseInt(rs.getString("workingDays"));
                    int bonus = Integer.parseInt(rs.getString("bonus"));

                    // Calculate salary
                    int totalEarnings = workingDays * (basicpay/30) + bonus;
                    int salary = (int) (totalEarnings * 0.95);

                    // Convert salary to String before setting it
                    grossSalary.setText(String.valueOf(salary));
                    
                  

                   
              }
              else{
                  JOptionPane.showMessageDialog(null, "Your Employee Id is invalid");
              }
        } catch (SQLException ex) {
            Logger.getLogger(salarySlip.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(salarySlip.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_GetSlipActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GetSlip;
    private javax.swing.JDesktopPane SalaryDesktop;
    private javax.swing.JLabel basicPay;
    private javax.swing.JLabel bonus;
    private javax.swing.JLabel department;
    private javax.swing.JLabel email;
    private javax.swing.JLabel grossSalary;
    private javax.swing.JLabel hours;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel name;
    private javax.swing.JLabel position;
    private javax.swing.JLabel tax;
    // End of variables declaration//GEN-END:variables
}
